import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  openMark,
  closeMark,
  scanMarks,
  findBlock,
  replaceBlock,
  unknownFamilies,
  FAMILIES,
} from '../../lib/marks.mjs';

const SPANISH = [
  '# Project',
  '',
  '<!-- capa1:inicio · generado desde el arnés · no editar a mano -->',
  'the old block',
  '<!-- capa1:fin -->',
  '',
  'text of the project that must not be touched',
].join('\n');

const ENGLISH = [
  '<!-- layer1:start · generated by the harness · do not edit by hand -->',
  'the block',
  '<!-- layer1:end -->',
].join('\n');

test('it reads the Spanish marks still deployed', () => {
  const found = findBlock(SPANISH, 'layer1');
  assert.equal(found.language, 'es');
  assert.equal(found.inner.trim(), 'the old block');
});

test('and it reads the English ones', () => {
  const found = findBlock(ENGLISH, 'layer1');
  assert.equal(found.language, 'en');
  assert.equal(found.inner.trim(), 'the block');
});

// 🔴 The migration: reading Spanish and writing English on the pass the
// harness already makes. No campaign, no file opened by hand.
test('replacing a Spanish block writes it back in English', () => {
  const out = replaceBlock(SPANISH, 'layer1', 'the new block');
  assert.match(out, /<!-- layer1:start · generated by the harness/);
  assert.match(out, /<!-- layer1:end -->/);
  assert.doesNotMatch(out, /capa1/);
});

// 🔴 The promise that makes a tool writing into someone else's repo
// acceptable: nothing outside the marks changes.
test('nothing outside the marks is touched', () => {
  const out = replaceBlock(SPANISH, 'layer1', 'whatever');
  assert.match(out, /^# Project\n/);
  assert.match(out, /text of the project that must not be touched$/);
});

// 🔴 The reason the whole mark is translated and not just its key: the old
// body names where the block came from. ⚠️ The fixture above says "el arnés"
// and not the real name on purpose — writing the private repo's name here
// would be the very leak this project guards against, and the leak guard
// caught it in this file on 2026-09-06.
test('the old body does not survive the migration', () => {
  const out = replaceBlock(SPANISH, 'layer1', 'x');
  assert.doesNotMatch(out, /generado desde/);
  assert.doesNotMatch(out, /no editar a mano/);
  assert.match(out, /generated by the harness/);
});

test('a missing block returns null instead of guessing', () => {
  assert.equal(findBlock('nothing here', 'layer1'), null);
  assert.equal(replaceBlock('nothing here', 'layer1', 'x'), null);
});

test('an opener with no closer is not a block', () => {
  assert.equal(findBlock('<!-- layer1:start · x -->\nbody', 'layer1'), null);
});

test('an unknown family throws rather than being written', () => {
  assert.throws(() => openMark('capas'), /unknown mark family/);
  assert.throws(() => closeMark('layer3'), /unknown mark family/);
});

// The guard's input: someone inventing a mark must fail loudly, not be
// silently ignored.
test('unknown families are reported', () => {
  const text = '<!-- invented:start -->x<!-- invented:end -->';
  assert.deepEqual(unknownFamilies(text), ['invented']);
  assert.deepEqual(unknownFamilies(ENGLISH), []);
});

test('all four families are recognised in both languages', () => {
  const es = ['capa1', 'capa2', 'reglas', 'reparaciones'];
  for (const [i, family] of FAMILIES.entries()) {
    const text = `<!-- ${es[i]}:inicio -->a<!-- ${es[i]}:fin -->`;
    assert.equal(findBlock(text, family).inner, 'a', `${es[i]} → ${family}`);
    assert.equal(scanMarks(text)[0].language, 'es');
  }
});

test('two families in one file do not cross', () => {
  const text = [
    '<!-- capa1:inicio -->',
    'one',
    '<!-- capa1:fin -->',
    '<!-- capa2:inicio -->',
    'two',
    '<!-- capa2:fin -->',
  ].join('\n');
  assert.equal(findBlock(text, 'layer1').inner.trim(), 'one');
  assert.equal(findBlock(text, 'layer2').inner.trim(), 'two');
});
