import { test } from 'node:test';
import assert from 'node:assert/strict';

import { stripBlocks, STRIPPED, CLEAN } from '../../lib/uninstall.mjs';
import { readFileSync } from 'node:fs';

import { plan } from '../../lib/propagate.mjs';

const withBlock = [
  '# A project',
  '',
  'Mine, above.',
  '',
  '<!-- layer1:start · x -->',
  'the harness wrote this',
  '<!-- layer1:end -->',
  '',
  'Mine, below.',
  '',
].join('\n');

// 🔴 The whole promise of the marks, read backwards: removing a block is easier
// than writing one, because writing has to decide where it goes and removing
// only has to read two comments.
test('the block goes and everything outside it stays', () => {
  const { next, removed, action, violation } = stripBlocks(withBlock);
  assert.equal(violation, null);
  assert.deepEqual(removed, ['layer1']);
  assert.equal(action, STRIPPED);
  assert.doesNotMatch(next, /layer1:/);
  assert.doesNotMatch(next, /the harness wrote this/);
  for (const line of ['# A project', 'Mine, above.', 'Mine, below.']) {
    assert.ok(next.includes(line), `${line} was lost`);
  }
});

// The seam closes, and only the seam: a block sat between blank lines, so
// removing it must not leave two where the project had one.
test('the seam is closed without touching spacing elsewhere', () => {
  const { next } = stripBlocks(withBlock);
  assert.doesNotMatch(next, /\n\n\n/, 'a double blank line was left behind');
  assert.match(next, /Mine, above\.\n\nMine, below\./);
});

test('a file with no block of ours is reported clean, not rewritten', () => {
  const plain = '# Theirs\n\nnothing of ours\n';
  const { action, next, removed } = stripBlocks(plain);
  assert.equal(action, CLEAN);
  assert.deepEqual(removed, []);
  assert.equal(next, plain, 'a clean file was rewritten');
});

// 🔴 Same refusal as `propagate`, and for the same reason: the span
// cannot be read one way only, so guessing would delete the project's prose.
test('a file whose marks do not pair is refused, not stripped', () => {
  const broken = '# X\n\n<!-- layer1:start · x -->\nhalf a block\n\nMine.\n';
  const { violation, next } = stripBlocks(broken);
  assert.ok(violation, 'an unclosed mark was stripped anyway');
  assert.match(violation.reason, /unmatched 'layer1' opener/);
  assert.equal(next, broken);
  assert.ok(next.includes('Mine.'));
});

test('two blocks of one family are refused too', () => {
  const twice =
    '<!-- layer1:start · x -->\na\n<!-- layer1:end -->\nmine\n' +
    '<!-- layer1:start · x -->\nb\n<!-- layer1:end -->\n';
  assert.ok(stripBlocks(twice).violation);
});

// The round trip, which is the only claim that matters: what a project had
// before the harness touched it is what it has after the harness is removed.
test('🔴 propagate then uninstall gives back what was outside the marks', () => {
  const original = '# Theirs\n\nOne line of theirs.\n\nAnd another.\n';
  const [grafted] = plan([{ path: 'a.md', text: original }], 'layer1', 'BLOCK');
  assert.ok(grafted.next.includes('BLOCK'), 'nothing was grafted');

  const { next } = stripBlocks(grafted.next);
  assert.equal(next, original, 'the round trip did not give the file back');
});

// 🔴 The `rules` family is written as ONE comment holding both marks, because
// it is guidance that must not show in rendered Markdown — and this scanner
// only reads the two-comment shape. Measured on 2026-09-07: **this harness's
// own templates/SESSION.md and templates/DECISIONS.md fail this check**, so
// every project seeded from them carries a block nothing updates and nothing
// removes. The refusal is right; calling it a broken file was not.
// `rules` is retired: its one-comment block is the project's text now, and
// uninstall leaves it exactly as it is.
test('a retired rules block is left alone', () => {
  const seeded = [
    '# SESSION',
    '',
    'Where we left it.',
    '',
    '<!-- rules:start · template SESSION v1 · generated by the harness',
    '',
    '  WHEN: as a task closes, not as the session closes.',
    '',
    '  rules:end -->',
    '',
  ].join('\n');

  const { violation, next } = stripBlocks(seeded);
  assert.equal(violation ?? null, null);
  assert.equal(next, seeded, 'a retired block was changed');

  // And a genuinely broken file still says so, in its own words.
  const broken = '<!-- layer1:start · x -->\nhalf a block\n';
  assert.match(stripBlocks(broken).violation.reason, /unmatched 'layer1'/);
});

// 🔴 The harness's own moulds must not fail its own check without saying why.
// This is the one that would have caught it on the day the shape diverged.
test("🔴 this harness's own templates are read, or the reason is the shape", () => {
  const here = new URL('../../templates/', import.meta.url);
  for (const name of ['SESSION.md', 'DECISIONS.md']) {
    const text = readFileSync(new URL(name, here), 'utf8');
    const { violation } = stripBlocks(text);
    if (!violation) continue;
    assert.equal(
      violation.shape,
      'one-comment',
      `templates/${name} is refused as broken: ${violation.reason}`,
    );
  }
});

// 🔴 A command nobody is told about is a command nobody has. The uninstall is
// what makes trying this harness reversible, and on 2026-09-07 it appeared in
// neither the README nor AGENTS.md — the same defect as the probe's flags, one
// day later.
test('the uninstall is documented where someone would look', () => {
  const here = new URL('../../', import.meta.url);
  const readme = readFileSync(new URL('README.md', here), 'utf8');
  const agents = readFileSync(new URL('AGENTS.md', here), 'utf8');
  assert.match(readme, /pnpm run uninstall/, 'the README does not mention it');
  assert.match(agents, /pnpm run uninstall/, 'AGENTS.md does not mention it');
  // And the README says the two things that decide whether it is safe to run.
  assert.match(readme, /never deleted/i);
  assert.match(readme, /With neither mark nor seal\s+it removes nothing/);
});
