// The marks that delimit generated blocks inside a project's own files.
//
// Two languages on purpose: files already in the wild carry Spanish marks, so
// this **reads both and writes only the new one**. They migrate on the pass the
// harness already makes — no campaign, no file opened by hand. Spanish stays
// readable for as long as a harnessed repo may still carry it.
//
// 🔴 The whole mark is translated, not just its key. The old body names the
// private repo the harness came from, so keeping it would ship that name into
// every project.

// `layer1` is written and updated. `layer2` is no longer written, and is still
// recognised so a block of it can be removed.
export const FAMILIES = ['layer1', 'layer2'];

// Spanish key → English family, read so old files migrate on the next pass.
export const LEGACY = {
  capa1: 'layer1',
  capa2: 'layer2',
};

// 🔴 Retired on 2026-09-06, and kept here so anyone who meets one gets told
// what it was instead of a bare "unknown family".
//
// `repairs` was declared alongside the other families and **nothing ever wrote
// it**. Its source was a record of one private set of repos, which does not
// travel, so the harness was reserving a slot it could never fill — and a
// declared family nobody fills is indistinguishable from a broken one.
//
// **Removing it breaks nothing, measured.** A block still carrying the mark
// stops being managed and becomes ordinary project text, which `propagate`
// preserves byte for byte like everything outside the marks it owns. What
// changes is that the guard now names it, which is the point: an orphan block
// should be visible rather than quietly reserved.
//
// `rules` went the same way on 2026-09-17: it wrapped the guidance comment in
// the DECISIONS and SESSION templates, and nothing ever updated it. Its text is
// the project's once seeded; the mark is left as plain text, like `repairs`.
export const RETIRED = {
  repairs: 'repairs',
  reparaciones: 'repairs',
  rules: 'rules',
  reglas: 'rules',
};

const KEYS = { ...LEGACY };
for (const f of FAMILIES) KEYS[f] = f;

const NOTE = 'generated by the harness · do not edit by hand';

export function openMark(family) {
  assertFamily(family);
  return `<!-- ${family}:start · ${NOTE} -->`;
}

export function closeMark(family) {
  assertFamily(family);
  return `<!-- ${family}:end -->`;
}

function assertFamily(family) {
  if (!FAMILIES.includes(family)) {
    throw new Error(`unknown mark family: ${family}`);
  }
}

// Any key, either language, either delimiter word.
const ANY = /<!--\s*([a-zá-ú0-9]+):(start|end|inicio|fin)\b([^>]*)-->/gi;

const OPENERS = new Set(['start', 'inicio']);

// Every mark found, in order, each tagged with the language it was written in.
// This is what tells the harness when Spanish can be switched off, and what
// fails loudly on a family nobody declared.
export function scanMarks(text) {
  const out = [];
  for (const m of String(text).matchAll(ANY)) {
    const [, rawKey, word, rest] = m;
    const key = rawKey.toLowerCase();
    out.push({
      key,
      family: KEYS[key] ?? null,
      known: key in KEYS,
      // The key is what decides the language: it is the part that differs.
      language: key in LEGACY ? 'es' : 'en',
      opener: OPENERS.has(word.toLowerCase()),
      rest: rest.trim(),
      index: m.index,
      length: m[0].length,
    });
  }
  return out;
}

// The block of one family, whichever language it is written in. Returns the
// inner text plus the offsets of the whole block, so a caller can replace it
// without touching a byte outside the marks.
export function findBlock(text, family) {
  assertFamily(family);
  const marks = scanMarks(text);
  const open = marks.find((m) => m.family === family && m.opener);
  if (!open) return null;
  const close = marks.find(
    (m) => m.family === family && !m.opener && m.index > open.index,
  );
  if (!close) return null;
  return {
    language: open.language,
    start: open.index,
    end: close.index + close.length,
    innerStart: open.index + open.length,
    innerEnd: close.index,
    inner: String(text).slice(open.index + open.length, close.index),
    header: open.rest,
  };
}

// The block, rendered. **One place, and this is it.** It used to be assembled
// here and again in `propagate.renderBlock`, which is how the two drifted: the
// graft wrote one shape and the update wrote another, so a second pass never
// settled. Measured on 2026-09-06; the older comment already claimed a single
// assembly point and was wrong.
//
// 🔴 **The blank line on each side of the body is not cosmetic.** An HTML
// comment and a heading are two block elements, and Prettier puts a blank line
// between block elements in Markdown. Without them this tool and the formatter
// undo each other forever: `format` adds the line, `propagate` then reports the
// file as needing an update, and a project whose `verify` chains `format:check`
// — which layer 1 requires — can never be green after running both.
export function renderBlock(family, body) {
  return [
    openMark(family),
    '',
    String(body).trim(),
    '',
    closeMark(family),
  ].join('\n');
}

// Replace a family's block, rewriting its marks in English. This is how the
// migration happens: on the pass the harness already makes.
export function replaceBlock(text, family, body) {
  const found = findBlock(text, family);
  if (!found) return null;
  return (
    String(text).slice(0, found.start) +
    renderBlock(family, body) +
    String(text).slice(found.end)
  );
}

// Remove a family's block, marks and body, leaving one blank line where it was
// — two would be rewritten by Prettier and reported as a change on the next
// pass. Returns null when there is no block, like `replaceBlock`.
export function removeBlock(text, family) {
  const found = findBlock(text, family);
  if (!found) return null;
  const before = String(text).slice(0, found.start).trimEnd();
  const after = String(text).slice(found.end).trimStart();
  return [before, after].filter(Boolean).join('\n\n') + (after ? '' : '\n');
}

// Families present that nobody declared — the guard's input. An unknown family
// means someone invented a mark, and that must fail rather than be ignored.
export function unknownFamilies(text) {
  return [
    ...new Set(
      scanMarks(text)
        .filter((m) => !m.known)
        .map((m) => m.key),
    ),
  ];
}

// 🔴 An opener with no closer is NOT the same as a file with no marks, and
// `findBlock` returns null for both. Measured on 2026-09-07 on a repo whose
// `AGENTS.md` carried one unclosed `layer1:start`:
//
//   pass 1 — no closer, so the file looks unmarked and a whole block is
//            grafted at the end. The file survives, and now holds **two
//            openers and one closer**.
//   pass 2 — the broken opener at the top pairs with the grafted closer at
//            the bottom, everything between them is called "the block", and
//            the project's own prose is replaced by it. Reported as a plain
//            `update`, exit 0.
//
// The guard that exists to stop this could not: `outside()` is built on
// `findBlock`, so it computed the same wrong span before and after and found
// them equal. **A safety check written on top of the broken function will
// certify the break.** So the imbalance is answered here, at the scanner,
// where both of them read from.
//
// Refusing is the only safe answer. This tool writes into other people's
// repositories, and it cannot know which of the two openers the project meant.
export function unbalanced(text, family) {
  const marks = scanMarks(text).filter((m) => m.family === family);
  if (!marks.length) return null;

  const openers = marks.filter((m) => m.opener);
  const closers = marks.filter((m) => !m.opener);

  // 🔴 Two complete blocks of one family are balanced, so the pairing test
  // below waves them through — and `planFile` only ever replaces the first.
  // Measured on 2026-09-07: the first block updated, the second left as it
  // was, the report said `1 to update` and exit 0. No data is lost; what the
  // file ends up holding is **two different versions of layer 1 side by
  // side**, and the agent reading it gets contradictory rules. That is the
  // exact opposite of what a tool called `propagate` exists to guarantee,
  // and it is silent and permanent. Rewriting both would leave the file
  // duplicated too, only consistently: which of the two the project meant is
  // not something this tool can know.
  if (openers.length > 1 && openers.length === closers.length) {
    return {
      reason: `${openers.length} separate '${family}' blocks in one file`,
      at: openers[1].index,
    };
  }

  if (openers.length === closers.length) {
    // Balanced by count is not balanced in order: `end … start` pairs nothing.
    for (let i = 0; i < openers.length; i++) {
      if (openers[i].index > closers[i].index) {
        return {
          reason: `a '${family}' block closes before it opens`,
          at: closers[i].index,
        };
      }
    }
    return null;
  }
  const more = openers.length > closers.length ? 'opener' : 'closer';
  const n = Math.abs(openers.length - closers.length);
  return {
    reason:
      `${n} unmatched '${family}' ${more}${n === 1 ? '' : 's'}: ` +
      `${openers.length} start, ${closers.length} end`,
    at: (openers.length > closers.length ? openers : closers).at(-1).index,
  };
}
